spring:
  profiles:
    active: db, core, api
  messages:
    encoding: UTF-8

server:
  port: 13800

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    cn.coreqi.api:  DEBUG
    cn.coreqi:  ERROR

swagger:
  production: false
