package cn.coreqi.db.dao;

import cn.coreqi.db.domain.TMenuRole;
import cn.coreqi.db.domain.TMenuRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    long countByExample(TMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    int deleteByExample(TMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    int insert(TMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    int insertSelective(TMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    TMenuRole selectOneByExample(TMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    TMenuRole selectOneByExampleSelective(@Param("example") TMenuRoleExample example, @Param("selective") TMenuRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    List<TMenuRole> selectByExampleSelective(@Param("example") TMenuRoleExample example, @Param("selective") TMenuRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    List<TMenuRole> selectByExample(TMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    TMenuRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TMenuRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    TMenuRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMenuRole record, @Param("example") TMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMenuRole record, @Param("example") TMenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMenuRole record);
}